services:
  baciasiatici-addon:
    build: .
    container_name: baciasiatici
    ports:
      - "3000:3000"
    volumes:
      - ./cache:/app/cache
    env_file:
      - .env
    restart: unless-stopped
